### PR TITLE
MolsMatrixToGridImage post

### PR DESCRIPTION
**Pull request by bertiewooster**
This is a blog post explaining MolsMatrixToGridImage, a new feature in the 2023.09.1 RDKit release.

### CODE REVIEW

**Review by greglandrum — COMMENTED** [review]
Thanks for doing the guest post!
I'm happy to merge this as is, but I would suggest moving the use cases (examples) up before the explanation of each of the parameters. That reference section is useful, but it's not really something super interesting to read through and I think it might be nice to have your (well thought through) examples, which nicely demonstrate *why* someone might want to use this functionality, show up earlier so that they are more likely to catch peoples' attention.

**Comment by bertiewooster** [comment]
Glad to contribute, Greg! Thanks for your perspective on what's most interesting. Sure thing, I'll reorder those sections.

**Comment by bertiewooster** [comment]
I reordered those sections, and moved the exhaustive example into the parameters section. I also put try...except blocks around the cells designed to give errors, which both allows the notebook to run in its entirety and makes the error messages take up much less vertical space.

**Review by greglandrum — APPROVED** [review]
LGTM

**Comment by bertiewooster** [comment]
Thanks for posting @greglandrum! Nice choice of subtitle and graphic on the [blog homepage](https://greglandrum.github.io/rdkit-blog/).

I noticed a few formatting issues, some due to how Markdown was converted to HTML, so I'll submit a follow-up PR. The one that could cause the most confusion is that `-` were not rendered as bullets below:

> A borderline situation is if each row will have the same number of molecules n (n = 2 below): you can create the same grid using either - MolsToGridImage(molsPerRow=n), for example MolsToGridImage([mol1a, mol1b, mol2a, mol2b, mol3a, mol3b], molsPerRow=2). - MolsMatrixToGridImage with n molecules in each row,...


It should appear as:

> A borderline situation is if each row will have the same number of molecules n (n = 2 below): you can create the same grid using either 
>- MolsToGridImage(molsPerRow=n), for example MolsToGridImage([mol1a, mol1b, mol2a, mol2b, mol3a, mol3b], molsPerRow=2). 
>- MolsMatrixToGridImage with n molecules in each row,...

If you've resolved that issue in the past and remember how, please let me know how.

**Comment by greglandrum** [comment]
> If you've resolved that issue in the past and remember how, please let me know how.

I will try to clear it up today and update the post

**Comment by bertiewooster** [comment]
Thanks. Could be as simple as putting a blank line before the first '-'.

**Comment by greglandrum** [comment]
> Thanks. Could be as simple as putting a blank line before the first '-'.

Yeah, I think that's likely it

**Comment by bertiewooster** [comment]
I made a [new PR](https://github.com/greglandrum/rdkit_blog/pull/17) for the changes.

**Pull request merged**
